//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HylandMedConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HylandMedConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string STR_CLEAR_MESSAGES {
            get {
                return ResourceManager.GetString("STR_CLEAR_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove old messages.  The most recent {0} message(s) will be kept..
        /// </summary>
        public static string STR_CLEAR_MESSAGES_TOOLTIP {
            get {
                return ResourceManager.GetString("STR_CLEAR_MESSAGES_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string STR_ERROR {
            get {
                return ResourceManager.GetString("STR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are already 4 players ready to play foosball.
        /// </summary>
        public static string STR_ERROR_TOO_MANY_FOOZ {
            get {
                return ResourceManager.GetString("STR_ERROR_TOO_MANY_FOOZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foosball Game Ready.
        /// </summary>
        public static string STR_FOOZ_GAME_READY {
            get {
                return ResourceManager.GetString("STR_FOOZ_GAME_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed: {0}.
        /// </summary>
        public static string STR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("STR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyland Meditech Config Tool v{0}.
        /// </summary>
        public static string STR_MAIN_TITLE {
            get {
                return ResourceManager.GetString("STR_MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} Now Available.
        /// </summary>
        public static string STR_NEW_VERSION_AVAILABLE_NOTIFICATION {
            get {
                return ResourceManager.GetString("STR_NEW_VERSION_AVAILABLE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting....
        /// </summary>
        public static string STR_RECONNECTING {
            get {
                return ResourceManager.GetString("STR_RECONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is down, attempting to reconnect.
        /// </summary>
        public static string STR_RECONNECTING_TOOLTIP {
            get {
                return ResourceManager.GetString("STR_RECONNECTING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected • {0:t}.
        /// </summary>
        public static string STR_SERVER_DOWN {
            get {
                return ResourceManager.GetString("STR_SERVER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected • {0:t}.
        /// </summary>
        public static string STR_SERVER_UP {
            get {
                return ResourceManager.GetString("STR_SERVER_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Team:.
        /// </summary>
        public static string STR_TEAM_ONE {
            get {
                return ResourceManager.GetString("STR_TEAM_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Team:.
        /// </summary>
        public static string STR_TEAM_TWO {
            get {
                return ResourceManager.GetString("STR_TEAM_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Available.
        /// </summary>
        public static string STR_UPGRADE_AVAILABLE {
            get {
                return ResourceManager.GetString("STR_UPGRADE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to the latest version.
        /// </summary>
        public static string STR_UPGRADE_AVAILABLE_TOOLTIP {
            get {
                return ResourceManager.GetString("STR_UPGRADE_AVAILABLE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logged on • {1:t}.
        /// </summary>
        public static string STR_USER_LOGGED_ON {
            get {
                return ResourceManager.GetString("STR_USER_LOGGED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logged on.
        /// </summary>
        public static string STR_USER_LOGGED_ON_NOTIFICATION {
            get {
                return ResourceManager.GetString("STR_USER_LOGGED_ON_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logged off • {1:t}.
        /// </summary>
        public static string STR_USER_LOGGED_OUT {
            get {
                return ResourceManager.GetString("STR_USER_LOGGED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logged off.
        /// </summary>
        public static string STR_USER_LOGGED_OUT_NOTIFICATION {
            get {
                return ResourceManager.GetString("STR_USER_LOGGED_OUT_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no longer ready for fooz at: {1}.
        /// </summary>
        public static string STR_USER_NOT_READY_FOR_FOOZ {
            get {
                return ResourceManager.GetString("STR_USER_NOT_READY_FOR_FOOZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready for foosball.
        /// </summary>
        public static string STR_USER_READY_FOR_FOOZ {
            get {
                return ResourceManager.GetString("STR_USER_READY_FOR_FOOZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sent a message.
        /// </summary>
        public static string STR_USER_SENT_MESSAGE {
            get {
                return ResourceManager.GetString("STR_USER_SENT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!  Type /help for more information..
        /// </summary>
        public static string STR_WELCOME_MESSAGE {
            get {
                return ResourceManager.GetString("STR_WELCOME_MESSAGE", resourceCulture);
            }
        }
    }
}
